export enum NotesTemplateTrigger {
    // Placement request & matching
    PLACEMENT_REQUEST_SUBMITTED = 'PLACEMENT_REQUEST_SUBMITTED',
    INDUSTRY_MATCH_IDENTIFIED = 'INDUSTRY_MATCH_IDENTIFIED',

    // Workplace decision (Student)
    WORKPLACE_APPROVED_BY_STUDENT = 'WORKPLACE_APPROVED_BY_STUDENT',
    WORKPLACE_REJECTED_BY_STUDENT = 'WORKPLACE_REJECTED_BY_STUDENT',

    // Workplace decision (RTO)
    WORKPLACE_APPROVED_BY_RTO = 'WORKPLACE_APPROVED_BY_RTO',
    WORKPLACE_REJECTED_BY_RTO = 'WORKPLACE_REJECTED_BY_RTO',

    // Workplace decision (Industry)
    WORKPLACE_APPROVED_BY_INDUSTRY = 'WORKPLACE_APPROVED_BY_INDUSTRY',
    WORKPLACE_REJECTED_BY_INDUSTRY = 'WORKPLACE_REJECTED_BY_INDUSTRY',

    // Appointments
    APPOINTMENT_SCHEDULED = 'APPOINTMENT_SCHEDULED',
    APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
    APPOINTMENT_INCOMPLETE = 'APPOINTMENT_INCOMPLETE',

    // Placement schedule
    PLACEMENT_SCHEDULE_CREATED = 'PLACEMENT_SCHEDULE_CREATED',

    // Agreement lifecycle
    AGREEMENT_INITIATED = 'AGREEMENT_INITIATED',
    AGREEMENT_APPROVED_BY_RTO = 'AGREEMENT_APPROVED_BY_RTO',
    AGREEMENT_SIGNED = 'AGREEMENT_SIGNED',

    // Placement lifecycle
    PLACEMENT_STARTED = 'PLACEMENT_STARTED',
    PLACEMENT_IN_PROGRESS = 'PLACEMENT_IN_PROGRESS',
    MID_PLACEMENT_REVIEW_COMPLETED = 'MID_PLACEMENT_REVIEW_COMPLETED',
    PLACEMENT_COMPLETED = 'PLACEMENT_COMPLETED',

    // Workplace eligibility (Student-provided)
    WORKPLACE_SUBMITTED = 'WORKPLACE_SUBMITTED',
    WORKPLACE_ELIGIBLE = 'WORKPLACE_ELIGIBLE',
    WORKPLACE_INELIGIBLE = 'WORKPLACE_INELIGIBLE',
}

export interface NoteTemplateType {
    id: number
    isActive: boolean
    createdAt: Date
    updatedAt: Date
    type: string
    subject: string
    successContent: string
    failureContent: string
    sequenceNo: number
    trigger: NotesTemplateTrigger
}
