export enum PermissionType {
    /* -------------------- ACTION REQUIRED -------------------- */
    SIGN_DOCUMENTS = 'SIGN_DOCUMENTS',
    APPROVE_PLACEMENTS = 'APPROVE_PLACEMENTS',
    SUBMISSIONS = 'SUBMISSIONS',
    RESOLVE_ISSUES = 'RESOLVE_ISSUES',
    /* -------------------- STUDENTS & PLACEMENTS -------------------- */
    ALL_STUDENTS = 'ALL_STUDENTS',
    PLACEMENT_REQUESTS = 'PLACEMENT_REQUESTS',
    STUDENT_SCHEDULE = 'STUDENT_SCHEDULE',
    IMPORT_STUDENTS = 'IMPORT_STUDENTS',
    CHANGE_WORKPLACE_STATUS = 'CHANGE_WORKPLACE_STATUS',
    CHANGE_WORKPLACE_ADDRESS = 'CHANGE_WORKPLACE_ADDRESS',

    /* -------------------- COMMUNICATIONS -------------------- */
    EMAILS = 'EMAILS',
    TEXT_MESSAGES = 'TEXT_MESSAGES',
    APPOINTMENTS = 'APPOINTMENTS',
    AUTO_SUPPORT_TICKETS = 'AUTO_SUPPORT_TICKETS',
    TEAM_TICKETS = 'TEAM_TICKETS',
    NOTIFICATIONS = 'NOTIFICATIONS',
    /* -------------------- MANAGE / SETUP -------------------- */
    SETUP_AUTOMATION = 'SETUP_AUTOMATION',
    LIST_ALL_INDUSTRIES = 'LIST_ALL_INDUSTRIES',
    TEAM_MANAGEMENT = 'TEAM_MANAGEMENT',
    COURSES = 'COURSES',
    /* -------------------- MORE TOOLS -------------------- */
    DATA_STORAGE = 'DATA_STORAGE',
    REPORTS = 'REPORTS',
    SUPPORT = 'SUPPORT',
    SETTINGS = 'SETTINGS',
    /* -------------------- BILLING & PACKAGES -------------------- */
    PACKAGE_MANAGEMENT = 'PACKAGE_MANAGEMENT',
    BILLING = 'BILLING',
    PRICING_TIERS = 'PRICING_TIERS',
    ADD_ONS = 'ADD_ONS',
    NETWORK_CREDIT_PACKAGES = 'NETWORK_CREDIT_PACKAGES',
    NETWORK_PACKS = 'NETWORK_PACKS',
    /* -------------------- AI / NETWORK UNLOCKABLE FEATURES -------------------- */
    AI_SEARCH = 'AI_SEARCH',
    TALENT_POOL_ACCESS = 'TALENT_POOL_ACCESS',
    BULK_STUDENT_MATCHING = 'BULK_STUDENT_MATCHING',
    /* -------------------- INDUSTRY & WORKPLACE -------------------- */
    ALLOW_WORKPLACE_REQUEST_APPROVAL = 'ALLOW_WORKPLACE_REQUEST_APPROVAL',
    ALLOW_STUDENT_NEED_WORKPLACE = 'ALLOW_STUDENT_NEED_WORKPLACE',
    ALLOW_STUDENT_OWN_WORKPLACE = 'ALLOW_STUDENT_OWN_WORKPLACE',
    CANCEL_WORKPLACE = 'CANCEL_WORKPLACE',
    CAN_PERFORM_INDUSTRY_ACTIONS = 'CAN_PERFORM_INDUSTRY_ACTIONS',
    /* -------------------- STUDENT & PROFILE CONTROLS -------------------- */
    ALLOW_LOGBOOK = 'ALLOW_LOGBOOK',
    ALLOW_UPDATE_PROFILE = 'ALLOW_UPDATE_PROFILE',
    ALLOW_NEW_DASHBOARD = 'ALLOW_NEW_DASHBOARD',
    ALLOW_AUTO_COMPLETE = 'ALLOW_AUTO_COMPLETE',
    ALLOW_PARTIAL_SUBMISSION = 'ALLOW_PARTIAL_SUBMISSION',
    CAN_VIEW_PAYMENT_STATUS = 'CAN_VIEW_PAYMENT_STATUS',
    ALLOW_SCHEDULE_EMAIL = 'ALLOW_SCHEDULE_EMAIL',
    ALLOW_AUTO_FETCH_CHECKLIST = 'ALLOW_AUTO_FETCH_CHECKLIST',
    /* -------------------- SYSTEM / ACCOUNT CONTROLS -------------------- */
    ARCHIVE = 'ARCHIVE',
    BLOCK = 'BLOCK',
    INVOICE_PERMISSION = 'INVOICE_PERMISSION',
    AUTO_REPORT = 'AUTO_REPORT',
    SELF_PAYMENT = 'SELF_PAYMENT',
    ALLOW_LOGIN_AFTER_HOURS = 'ALLOW_LOGIN_AFTER_HOURS',
    /* -------------------- VISIBILITY / ACCESS CONTROL -------------------- */
    CAN_VIEW_ALL_STUDENTS = 'CAN_VIEW_ALL_STUDENTS',
    CAN_VIEW_STUDENT_DETAIL = 'CAN_VIEW_STUDENT_DETAIL',
    CAN_VIEW_INDUSTRY_DETAIL = 'CAN_VIEW_INDUSTRY_DETAIL',
    VIEW_ALL_TICKETS = 'VIEW_ALL_TICKETS',
    VIEW_ASSIGNED_TICKETS = 'VIEW_ASSIGNED_TICKETS',
    /* -------------------- INDUSTRY LISTING / SOURCING -------------------- */
    ALLOW_GLOBAL_SEARCH = 'ALLOW_GLOBAL_SEARCH',
    ALLOW_INDUSTRY_LISTING = 'ALLOW_INDUSTRY_LISTING',
    CAN_IMPORT_INDUSTRY = 'CAN_IMPORT_INDUSTRY',
    CAN_IMPORT_INDUSTRY_LISTING = 'CAN_IMPORT_INDUSTRY_LISTING',
    TOGGLE_DISTRIBUTE_INDUSTRIES = 'TOGGLE_DISTRIBUTE_INDUSTRIES',
    /* -------------------- RTO  LISTING / SOURCING -------------------- */
    ALLOW_RTO_LISTING = 'ALLOW_RTO_LISTING',
    CAN_IMPORT_RTO_LISTING = 'CAN_IMPORT_RTO_LISTING',
    UPDATE_RTO_PERMISSION = 'UPDATE_RTO_PERMISSION',
    MANAGE_RTOS = 'MANAGE_RTOS',
    VIEW_RTO_DETAIL = 'VIEW_RTO_DETAIL',
    /* -------------------- MATCHING & AI -------------------- */
    START_MATCHING = 'START_MATCHING',
    /* -------------------- ADMIN (SKILTRAK) -------------------- */
    MANAGE_USERS = 'MANAGE_USERS',

    MANAGE_STUDENTS = 'MANAGE_STUDENTS',
    MANAGE_INDUSTRIES = 'MANAGE_INDUSTRIES',
    MANAGE_COORDINATORS = 'MANAGE_COORDINATORS',
    MANAGE_TEAMS = 'MANAGE_TEAMS',
    MANAGE_KPIS = 'MANAGE_KPIS',
    MANAGE_TALENT_POOL = 'MANAGE_TALENT_POOL',
    MANAGE_SECTORS = 'MANAGE_SECTORS',
    MANAGE_DOCUMENTS = 'MANAGE_DOCUMENTS',
    MANAGE_APPOINTMENTS = 'MANAGE_APPOINTMENTS',
    MANAGE_RPL = 'MANAGE_RPL',
    MANAGE_VOLUNTEERS = 'MANAGE_VOLUNTEERS',
    MANAGE_JOBS = 'MANAGE_JOBS',
    MANAGE_BLOGS = 'MANAGE_BLOGS',
    MANAGE_SUBSCRIBERS = 'MANAGE_SUBSCRIBERS',
    MANAGE_SMS = 'MANAGE_SMS',
    MANAGE_EMAILS = 'MANAGE_EMAILS',
    MANAGE_CALLS = 'MANAGE_CALLS',
    /* -------------------- RTO STUDENT PROFILE -------------------- */
    BOOK_STUDENT_APPOINTMENTS = 'BOOK_STUDENT_APPOINTMENTS',
    APPROVE_WORKPLACE_REQUEST = 'APPROVE_WORKPLACE_REQUEST',
    CANCEL_WORKPLACE_REQUEST = 'CANCEL_WORKPLACE_REQUEST',
    APPROVE_INDUSTRY_FROM_STUDENT_PROFILE = 'APPROVE_INDUSTRY_FROM_STUDENT_PROFILE',
    VIEW_INDUSTRY_PROFILE = 'VIEW_INDUSTRY_PROFILE',
    TERMINATE_PLACEMENT = 'TERMINATE_PLACEMENT',
    VIEW_SUPPORT_TICKETS = 'VIEW_SUPPORT_TICKETS',
    VIEW_INTERNAL_TICKETS = 'VIEW_INTERNAL_TICKETS',
    SNOOZE_STUDENT = 'SNOOZE_STUDENT',
    SEND_PASSWORD = 'SEND_PASSWORD',
    VIEW_PASSWORD = 'VIEW_PASSWORD',
    EDIT_PASSWORD = 'EDIT_PASSWORD',
    VIEW_VISITORS = 'VIEW_VISITORS',
    /* -------------------- RTO PLACEMENT PROFILE -------------------- */
    VIEW_PLACEMENT_PROFILE = 'VIEW_PLACEMENT_PROFILE',
    CAN_USE_CHATBOT = 'CAN_USE_CHATBOT',
}

export interface IPermission {
    id: number
    code: string
    name: string
    description?: string
    roles: string[]
    createdAt?: string
    updatedAt?: string
}

export interface CreatePermissionDto {
    code: string
    name: string
    description?: string
    roles: string[]
}

export type PermissionFormType = CreatePermissionDto
export interface IAssignedPermission {
    id: number
    isActive: boolean
    userId: number
    permissionId: number
    grantedById?: number
    grantedAt?: string
    expiresAt?: string | null
    createdAt?: string
    updatedAt?: string
    permission: IPermission
}
