export interface IndustryPartner {
    id: string
    name: string
    address: string
    location: string
    distance: number
    courses: string[]
    signedUp: boolean
    contacted: boolean
    emailSent: boolean
    interested?: boolean // true = interested, false = not interested, undefined = not contacted
}
export const AVATAR_COLORS = [
    '#C0C0C0',
    '#A8A8A8',
    '#909090',
    '#B8B8B8',
    '#D0D0D0',
    '#989898',
]

export const industryPartners: IndustryPartner[] = [
    {
        id: '1',
        name: 'Melbourne Training Institute',
        address: '123 Training Road, Melbourne',
        location: 'South-East Melbourne',
        distance: 5,
        courses: ['Cookery', 'Hospitality'],
        signedUp: true,
        contacted: true,
        emailSent: true,
    },
    {
        id: '2',
        name: 'City Skills Academy',
        address: '456 Business Lane, Melbourne',
        location: 'CBD Melbourne',
        distance: 10,
        courses: ['Business Administration', 'IT'],
        signedUp: true,
        contacted: true,
        emailSent: true,
    },
    {
        id: '3',
        name: 'Geelong TAFE',
        address: '789 Community Street, Geelong',
        location: 'Geelong',
        distance: 20,
        courses: ['Community Services', 'Aged Care'],
        signedUp: true,
        contacted: true,
        emailSent: true,
    },
    {
        id: '4',
        name: 'West Side Training',
        address: '101 Aged Care Avenue, Western Melbourne',
        location: 'Western Melbourne',
        distance: 15,
        courses: ['Aged Care'],
        signedUp: true,
        contacted: true,
        emailSent: true,
    },
    {
        id: '5',
        name: 'Regional Skills Hub',
        address: '202 Childcare Circle, Bendigo',
        location: 'Bendigo',
        distance: 30,
        courses: ['Childcare', 'Community Services'],
        signedUp: true,
        contacted: true,
        emailSent: true,
    },
    {
        id: '6',
        name: 'Ballarat Skills Centre',
        address: '303 Hospitality Highway, Ballarat',
        location: 'Ballarat',
        distance: 25,
        courses: ['Hospitality'],
        signedUp: true,
        contacted: true,
        emailSent: true,
    },
    {
        id: '7',
        name: 'Tech Training Victoria',
        address: '404 IT Intersection, CBD Melbourne',
        location: 'CBD Melbourne',
        distance: 10,
        courses: ['IT'],
        signedUp: true,
        contacted: true,
        emailSent: true,
    },
    // Future/Listing - Not Signed Up Partners
    {
        id: '8',
        name: 'Simmi Family daycare',
        address: '98 Opal Dr, Leopold VIC 3224',
        location: 'Geelong',
        distance: 8.46,
        courses: ['Childcare'],
        signedUp: false,
        contacted: true,
        emailSent: true,
        interested: true,
    },
    {
        id: '9',
        name: 'Leopold Kindergarten',
        address: '29 Kanimbla Ave, Leopold VIC 3224',
        location: 'Geelong',
        distance: 8.81,
        courses: ['Childcare'],
        signedUp: false,
        contacted: true,
        emailSent: true,
        interested: false,
    },
    {
        id: '10',
        name: 'Allanvale Preschool',
        address: '28 Allanvale Ave, Leopold VIC 3224',
        location: 'Geelong',
        distance: 9.33,
        courses: ['Childcare'],
        signedUp: false,
        contacted: false,
        emailSent: false,
        interested: undefined,
    },
    {
        id: '11',
        name: 'Golden Aged Care Centre',
        address: '45 Senior Street, Western Melbourne',
        location: 'Western Melbourne',
        distance: 12.5,
        courses: ['Aged Care'],
        signedUp: false,
        contacted: true,
        emailSent: true,
        interested: true,
    },
    {
        id: '12',
        name: 'Sunshine Community Hub',
        address: '67 Community Drive, Western Melbourne',
        location: 'Western Melbourne',
        distance: 14.2,
        courses: ['Community Services', 'Aged Care'],
        signedUp: false,
        contacted: false,
        emailSent: false,
        interested: undefined,
    },
    {
        id: '13',
        name: 'The Kitchen Co Restaurant',
        address: '89 Culinary Lane, South-East Melbourne',
        location: 'South-East Melbourne',
        distance: 6.7,
        courses: ['Cookery', 'Hospitality'],
        signedUp: false,
        contacted: true,
        emailSent: true,
        interested: false,
    },
    {
        id: '14',
        name: 'Harbour View Hotel',
        address: '120 Bay Parade, South-East Melbourne',
        location: 'South-East Melbourne',
        distance: 7.9,
        courses: ['Hospitality'],
        signedUp: false,
        contacted: false,
        emailSent: false,
        interested: undefined,
    },
    {
        id: '15',
        name: 'Coastal Cafe & Bistro',
        address: '15 Beachside Road, Geelong',
        location: 'Geelong',
        distance: 18.3,
        courses: ['Cookery', 'Hospitality'],
        signedUp: false,
        contacted: true,
        emailSent: true,
        interested: true,
    },
    {
        id: '16',
        name: 'Bendigo Business Solutions',
        address: '78 Corporate Court, Bendigo',
        location: 'Bendigo',
        distance: 28.6,
        courses: ['Business Administration'],
        signedUp: false,
        contacted: true,
        emailSent: false,
        interested: false,
    },
    {
        id: '17',
        name: 'Regional IT Services',
        address: '92 Tech Park, Bendigo',
        location: 'Bendigo',
        distance: 31.2,
        courses: ['IT'],
        signedUp: false,
        contacted: false,
        emailSent: false,
        interested: undefined,
    },
]
